POST http://localhost:8080/reserva
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGb290ZWQiLCJleHAiOjE2OTczMjg4MDMsInN1YiI6IjM2NC4xMzUuMTEwLTA3In0.fasnjrs3mgrZ4KyMZItUN-mtd4mEafv1Y_1A9VDbSPM

{
    "data": "2023-11-10",
    "horario": "15:00:00",
    "quadraId": 5,
    "usuarioId": 15
}